spring:
  application:
    name: arzuamber

  origin:
    url: https://arzuamber.com

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://arzuamber-db:5432/arzuamber-db
    #url: jdbc:postgresql://localhost:5435/arzuamber-db
    username: arzuamber_user
    password: arzuamber_pass
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  minio:
    url: http://arzuamber-blob-storage:9000
    #url: http://localhost:9000
    user: arzuamber_user
    password: arzuamber_pass
    bucket-name: arzuamber-bucket

  jwt:
    secret_keys: "RDDCT6me8cETAsAiABsYc0FwzLlu4CcNJWMBV8OdGt8Qrt2hleK1W/p/9K8kJuaNcqnsVgZ6PvfR2QcshYBGBqH3MJVekOHlQoyM9VspWkYFNovzBn/QOPiHyLGsaDhB/KIUleVCaMJK3YktQavVvGsFbld1QYXqnkeLZ9jb5tw="
    expiration: 604800000
    refresh-token:
      expiration: 604800000

  iyzico:
    api_key: wsXNHznkvp2vwa2uwPkTBatTldHuz0GZ
    secret_key: i00wXXujkkfzsbRFF8W9GDKhqCE8MWSR
    base_url: https://api.iyzipay.com
    #api_key: sandbox-4mlmZxqqpEvkFn61GClqGpDpt0cYZuA2
    #secret_key: sandbox-m4UURbHi8klCbIqCiCWsjlyJG8mTfuG4
    #base_url: https://sandbox-api.iyzipay.com

  #payment:
  #  callback-url: http://192.168.1.114:8080/v1/api/order/complete-threeds
  payment:
    callback-url: https://arzuamber.com/v1-api/order/complete-threeds

  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB